DROP DATABASE IF EXISTS POVCamaras;
CREATE DATABASE POVCamaras;
USE POVCamaras;

CREATE TABLE ROL(
    idRol    VARCHAR(3),
    nombreRol   VARCHAR(20) NOT NULL,
    CONSTRAINT PK_ROL PRIMARY KEY (idRol)
);

CREATE TABLE USUARIOS(
    idUsuario INT AUTO_INCREMENT,
    nombreUsuario  VARCHAR(50) NOT NULL,
    apellidos VARCHAR(50) NOT NULL,
    email VARCHAR(50) NOT NULL,
    direccion VARCHAR(100),
    telefono VARCHAR(15)NOT NULL,
    contrasena VARCHAR(50) NOT NULL,
    rol VARCHAR(3),
    CONSTRAINT PK_USUARIOS PRIMARY KEY (idUsuario),
    CONSTRAINT FK_ROL_USUARIO FOREIGN KEY  (rol) REFERENCES ROL(idRol)
);
CREATE TABLE PEDIDO(
    idPedido VARCHAR(100),
    nombreUsuario VARCHAR(50) NOT NULL,
    apellidos VARCHAR(50) NOT NULL,
    email VARCHAR(50) NOT NULL,
    direccion VARCHAR(100),
    precioTotal DECIMAL(10,2) NOT NULL,
    estadoPedido VARCHAR(20) NOT NULL,
    fechaPedido DATE NOT NULL,
    idUsuario INT,
    CONSTRAINT PK_PEDIDO PRIMARY KEY (idPedido),
    CONSTRAINT FK_PEDIDO_USUARIO FOREIGN KEY (idUsuario) REFERENCES USUARIOS(idUsuario)
);
CREATE TABLE CATEGORIA(
    idCategoria VARCHAR(100),
    nombreCategoria VARCHAR(50) NOT NULL,
    CONSTRAINT PK_CATEGORIA PRIMARY KEY (idCategoria)
);

CREATE TABLE PRODUCTO(
    idProducto VARCHAR(100),
    nombreProducto VARCHAR(50) NOT NULL,
    marca VARCHAR(50) NOT NULL,
    modelo VARCHAR(50) NOT NULL,
    descripcion VARCHAR(100),
    idCategoria VARCHAR(100),
    precioUnitario DECIMAL(10,2) NOT NULL,
    stock INT NOT NULL,
    imagen VARCHAR(100),
    CONSTRAINT PK_PRODUCTO PRIMARY KEY (idProducto),
    CONSTRAINT FK_PRODUCTO_CATEGORIA FOREIGN KEY (idCategoria) REFERENCES CATEGORIA(idCategoria)
);
CREATE TABLE CATEGORIA_PRODUCTO(
    idCategoria VARCHAR(100),
    idProducto VARCHAR(100),
    CONSTRAINT PK_CATEGORIA_PRODUCTO PRIMARY KEY (idProducto,idCategoria),
    CONSTRAINT FK_CATEGORIA_PRODUCTO_CATEGORIA FOREIGN KEY (idCategoria) REFERENCES CATEGORIA(idCategoria),
    CONSTRAINT FK_CATEGORIA_PRODUCTO_PRODUCTO FOREIGN KEY (idProducto) REFERENCES PRODUCTO(idProducto)
);

CREATE TABLE LINEA_PEDIDO(
    idLineaPedido VARCHAR(100),
    cantidad INT NOT NULL,
    precioUnitario DECIMAL(10,2) NOT NULL,
    idPedido VARCHAR(100),
    idProducto VARCHAR(100),
    subtotal DECIMAL(10,2) NOT NULL,
    CONSTRAINT PK_LINEA_PEDIDO PRIMARY KEY (idLineaPedido),
    CONSTRAINT FK_LINEA_PEDIDO_PEDIDO FOREIGN KEY (idPedido) REFERENCES PEDIDO(idPedido),
    CONSTRAINT FK_LINEA_PEDIDO_PRODUCTO FOREIGN KEY (idProducto) REFERENCES PRODUCTO(idProducto)
);

create TABLE ENVIO(
    idEnvio VARCHAR(100),
    numeroSeguimiento VARCHAR(100),
    fechaEnvio DATE NOT NULL,
    empresaEnvio VARCHAR(50) NOT NULL,
    idPedido VARCHAR(100),
    CONSTRAINT PK_ENVIO PRIMARY KEY (idEnvio),
    CONSTRAINT FK_ENVIO_PEDIDO FOREIGN KEY (idPedido) REFERENCES PEDIDO(idPedido)
);

INSERT INTO ROL VALUES ('ADM','Administrador'),('CLI','Cliente');